spring.application.name=4-th-year-project
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
server.port=8081
spring.datasource.username=postgres.kjfnaupuurpkbyazncnx
#spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload-dir=uploads
# Redis cache layer between Spring Boot and Supabase PostgreSQL

# Redis Cloud cache layer
spring.cache.type=redis
spring.data.redis.host=redis-18665.crce263.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=18665
spring.data.redis.username=default
#spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=60000

