spring.application.name=4-th-year-project
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres

spring.datasource.username=postgres.kjfnaupuurpkbyazncnx
spring.datasource.password=Srijan@#1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Redis cache layer between Spring Boot and Supabase PostgreSQL
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redis-18665.crce263.ap-south-1-1.ec2.cloud.redislabs.com}
spring.data.redis.port=${REDIS_PORT:18665}
spring.data.redis.password=${REDIS_PASSWORD:"yKmgWv5I6xAY0iBL42NZNrXvUcnzHSQm"}
spring.data.redis.timeout=60000
